sudo: false

language: go

# Versions of go that are explicitly supported by MachineLearning.
go:
 - 1.5.4
 - 1.6.3
 - 1.7.3

# Required for coverage, and testing.
before_install:
 - go get github.com/tealeg/xlsx
 - go get github.com/gonum/matrix/mat64
 - go get github.com/tonnerre/golang-pretty
